name: openaq_oracle
version: "1.0.0"
config-version: 2

profile: openaq_oracle

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

quoting:
  database: false
  identifier: false
  schema: false

models:
  openaq_oracle:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  openaq_oracle:
    +schema: seed

